java_library(
    name = "BoundBuffer",
    srcs = ["BoundBuffer.java"],
    deps = [],
)

java_library(
    name = "BoundBufferSemaphoreImpl",
    srcs = ["BoundBufferSemaphoreImpl.java"],
    deps = [":BoundBuffer"],
)

java_library(
    name = "BoundBufferMonitorImpl",
    srcs = ["BoundBufferMonitorImpl.java"],
    deps = [":BoundBuffer"],
)
