java_test(
    name = "MapImplTest",
    srcs = ["MapImplTest.java"],
    deps = [
        "//java/com/os/structures/map:IKeyHasher",
        "//java/com/os/structures/map:IMap",
        "//java/com/os/structures/map:MapImpl",
        "//third_party:junit4",
    ],
)
